title: across
email: glasnt@google.com
baseurl: ""
url: "https://whodoesthe.dev" 
twitter_username: google
github_username: google

plugins:
  - jekyll-feed

navbar:
  - title: About
    url: /about/
#  - title: News
#    url: /news/
  - title: Workshop
    url: /workshops/group/
  - title: GitHub
    url: https://github.com/google/across
  - title: Contact
    url: /contact/

#permalink: /news/:title